### ISSUE TITLE
Using with Bankai

### ISSUE THREAD

**Issue by jongacnik** [choojs/choop#13]
`choop` works great with with [`bankai`](https://github.com/choojs/bankai), however there is currently a bug (https://github.com/choojs/bankai/issues/341) with nested `.babelrc` files which will cause the server to crash. There are 2 solutions in the meantime:

Manually modify `bankai/lib/graph-script.js` by adding `babelrc: false` to the babelify config

OR

You can install some additional babel transforms in your project:

```
npm i -D babel-plugin-transform-class-properties \
babel-plugin-transform-react-jsx \
babel-preset-es2015 \
babel-preset-stage-0
```

**Comment by goto-bus-stop** [comment]
https://github.com/choojs/bankai/issues/341 is fixed by https://github.com/choojs/bankai/issues/352!
